FROM mcr.microsoft.com/devcontainers/go:1.21-bookworm

ARG USERNAME=vscode
USER $USERNAME

# Tools
RUN go install github.com/go-task/task/v3/cmd/task@latest \
    && go install github.com/cosmtrek/air@latest \
    && go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest \
    && go install github.com/swaggo/swag/cmd/swag@latest \
    && go install go.uber.org/mock/mockgen@latest
